version: "3.8"

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
      - MONGO_URI=mongodb://mongoadmin:ZentryMongo123@48.217.187.254:27017/Zentry?authSource=admin
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
    container_name: zentry-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: ZentryMongo123

